version: '3.8'
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "80:4000"
    volumes:
      - "./home/cristolfe/Documentos/dev-test/node_modules:/home/cristolfe/Documentos/dev-test/node_modules"
      - "./:/home/app"
